version: "3"
services:
  db:
    image: mysql
    restart: always
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysqldb


#  backend:
#    build:
#      context: .
#    command: gradle bootRun
#    container_name: backend
#    restart: on-failure
#    tty: true