spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true



  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: root
    password: 1234



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
